// <auto-generated />
using System;
using Lutra.Infrastructure.Sql;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lutra.Infrastructure.Sql.Migrations
{
    [DbContext(typeof(LutraDbContext))]
    [Migration("20260917195720_EnlargeVerspakketNaam")]
    partial class EnlargeVerspakketNaam
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lutra.Domain.Entities.BackgroundCommandJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActiveDeduplicationKey")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeduplicationKey")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastError")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTime?>("LeaseExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LeaseToken")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<Guid?>("ResultVerspakketId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Status", "LeaseExpiresAt");

                    b.HasIndex("Status", "NextAttemptAt");

                    b.HasIndex("Type", "ActiveDeduplicationKey")
                        .IsUnique()
                        .HasFilter("\"ActiveDeduplicationKey\" IS NOT NULL");

                    b.ToTable("BackgroundCommandJobs");
                });

            modelBuilder.Entity("Lutra.Domain.Entities.Beoordeling", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Aanbevolen")
                        .HasColumnType("boolean");

                    b.Property<int>("CijferBereiden")
                        .HasColumnType("integer");

                    b.Property<int>("CijferSmaak")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Tekst")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<Guid>("VerspakketId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VerspakketId");

                    b.ToTable("Beoordelingen");
                });

            modelBuilder.Entity("Lutra.Domain.Entities.Ingredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Eenheid")
                        .HasColumnType("integer");

                    b.Property<decimal>("Hoeveelheid")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<bool>("Inbegrepen")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("VerspakketId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VerspakketId");

                    b.ToTable("Ingredienten", t =>
                        {
                            t.HasCheckConstraint("CK_Ingredienten_Hoeveelheid", "\"Hoeveelheid\" > 0");
                        });
                });

            modelBuilder.Entity("Lutra.Domain.Entities.Supermarkt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Supermarkten");
                });

            modelBuilder.Entity("Lutra.Domain.Entities.Verspakket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AantalPersonen")
                        .HasColumnType("integer");

                    b.Property<string>("BronUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("PrijsInCenten")
                        .HasColumnType("integer");

                    b.Property<Guid>("SupermarktId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BronUrl")
                        .IsUnique()
                        .HasFilter("\"BronUrl\" IS NOT NULL");

                    b.HasIndex("SupermarktId");

                    b.ToTable("Verspaketten", t =>
                        {
                            t.HasCheckConstraint("CK_Verspaketten_AantalPersonen", "\"AantalPersonen\" BETWEEN 1 AND 10");

                            t.HasCheckConstraint("CK_Verspaketten_PrijsInCenten", "\"PrijsInCenten\" IS NULL OR \"PrijsInCenten\" >= 0");
                        });
                });

            modelBuilder.Entity("Lutra.Domain.Entities.VerspakketAllergeen", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Allergeen")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VerspakketId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VerspakketId", "Allergeen")
                        .IsUnique();

                    b.ToTable("VerspakketAllergenen");
                });

            modelBuilder.Entity("Lutra.Domain.Entities.VerspakketFoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsMainImage")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VerspakketId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VerspakketId");

                    b.ToTable("VerspakketFotos");
                });

            modelBuilder.Entity("Lutra.Domain.Entities.Voedingswaarde", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Basis")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("Eiwitten")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal?>("EnergieKcal")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal?>("EnergieKj")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal?>("Koolhydraten")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VerspakketId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Vetten")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal?>("Vezels")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal?>("WaarvanSuikers")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal?>("WaarvanVerzadigd")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal?>("Zout")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("VerspakketId", "Basis")
                        .IsUnique();

                    b.ToTable("Voedingswaarden", t =>
                        {
                            t.HasCheckConstraint("CK_Voedingswaarden_Eiwitten", "\"Eiwitten\" IS NULL OR \"Eiwitten\" >= 0");

                            t.HasCheckConstraint("CK_Voedingswaarden_EnergieKcal", "\"EnergieKcal\" IS NULL OR \"EnergieKcal\" >= 0");

                            t.HasCheckConstraint("CK_Voedingswaarden_EnergieKj", "\"EnergieKj\" IS NULL OR \"EnergieKj\" >= 0");

                            t.HasCheckConstraint("CK_Voedingswaarden_Koolhydraten", "\"Koolhydraten\" IS NULL OR \"Koolhydraten\" >= 0");

                            t.HasCheckConstraint("CK_Voedingswaarden_Vetten", "\"Vetten\" IS NULL OR \"Vetten\" >= 0");

                            t.HasCheckConstraint("CK_Voedingswaarden_Vezels", "\"Vezels\" IS NULL OR \"Vezels\" >= 0");

                            t.HasCheckConstraint("CK_Voedingswaarden_WaarvanSuikers", "\"WaarvanSuikers\" IS NULL OR CAST(\"Koolhydraten\" AS NUMERIC) IS NULL OR CAST(\"WaarvanSuikers\" AS NUMERIC) <= CAST(\"Koolhydraten\" AS NUMERIC)");

                            t.HasCheckConstraint("CK_Voedingswaarden_WaarvanVerzadigd", "\"WaarvanVerzadigd\" IS NULL OR CAST(\"Vetten\" AS NUMERIC) IS NULL OR CAST(\"WaarvanVerzadigd\" AS NUMERIC) <= CAST(\"Vetten\" AS NUMERIC)");

                            t.HasCheckConstraint("CK_Voedingswaarden_Zout", "\"Zout\" IS NULL OR \"Zout\" >= 0");
                        });
                });

            modelBuilder.Entity("Lutra.Domain.Entities.Beoordeling", b =>
                {
                    b.HasOne("Lutra.Domain.Entities.Verspakket", "Verspakket")
                        .WithMany("Beoordelingen")
                        .HasForeignKey("VerspakketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Verspakket");
                });

            modelBuilder.Entity("Lutra.Domain.Entities.Ingredient", b =>
                {
                    b.HasOne("Lutra.Domain.Entities.Verspakket", "Verspakket")
                        .WithMany("Ingredienten")
                        .HasForeignKey("VerspakketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Verspakket");
                });

            modelBuilder.Entity("Lutra.Domain.Entities.Verspakket", b =>
                {
                    b.HasOne("Lutra.Domain.Entities.Supermarkt", "Supermarkt")
                        .WithMany()
                        .HasForeignKey("SupermarktId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supermarkt");
                });

            modelBuilder.Entity("Lutra.Domain.Entities.VerspakketAllergeen", b =>
                {
                    b.HasOne("Lutra.Domain.Entities.Verspakket", "Verspakket")
                        .WithMany("Allergenen")
                        .HasForeignKey("VerspakketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Verspakket");
                });

            modelBuilder.Entity("Lutra.Domain.Entities.VerspakketFoto", b =>
                {
                    b.HasOne("Lutra.Domain.Entities.Verspakket", "Verspakket")
                        .WithMany("Fotos")
                        .HasForeignKey("VerspakketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Verspakket");
                });

            modelBuilder.Entity("Lutra.Domain.Entities.Voedingswaarde", b =>
                {
                    b.HasOne("Lutra.Domain.Entities.Verspakket", "Verspakket")
                        .WithMany("Voedingswaarden")
                        .HasForeignKey("VerspakketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Verspakket");
                });

            modelBuilder.Entity("Lutra.Domain.Entities.Verspakket", b =>
                {
                    b.Navigation("Allergenen");

                    b.Navigation("Beoordelingen");

                    b.Navigation("Fotos");

                    b.Navigation("Ingredienten");

                    b.Navigation("Voedingswaarden");
                });
#pragma warning restore 612, 618
        }
    }
}
