// <auto-generated />
using System;
using Lutra.Infrastructure.Sql;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lutra.Infrastructure.Sql.Migrations
{
    [DbContext(typeof(LutraDbContext))]
    [Migration("20260825181240_AddIngredienten")]
    partial class AddIngredienten
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lutra.Domain.Entities.Beoordeling", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Aanbevolen")
                        .HasColumnType("boolean");

                    b.Property<int>("CijferBereiden")
                        .HasColumnType("integer");

                    b.Property<int>("CijferSmaak")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Tekst")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<Guid>("VerspakketId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VerspakketId");

                    b.ToTable("Beoordelingen");
                });

            modelBuilder.Entity("Lutra.Domain.Entities.Ingredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Eenheid")
                        .HasColumnType("integer");

                    b.Property<decimal>("Hoeveelheid")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<bool>("Inbegrepen")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("VerspakketId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VerspakketId");

                    b.ToTable("Ingredienten", t =>
                        {
                            t.HasCheckConstraint("CK_Ingredienten_Hoeveelheid", "\"Hoeveelheid\" > 0");
                        });
                });

            modelBuilder.Entity("Lutra.Domain.Entities.Supermarkt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Supermarkten");
                });

            modelBuilder.Entity("Lutra.Domain.Entities.Verspakket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AantalPersonen")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("PrijsInCenten")
                        .HasColumnType("integer");

                    b.Property<Guid>("SupermarktId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SupermarktId");

                    b.ToTable("Verspaketten", t =>
                        {
                            t.HasCheckConstraint("CK_Verspaketten_AantalPersonen", "\"AantalPersonen\" BETWEEN 1 AND 10");

                            t.HasCheckConstraint("CK_Verspaketten_PrijsInCenten", "\"PrijsInCenten\" IS NULL OR \"PrijsInCenten\" >= 0");
                        });
                });

            modelBuilder.Entity("Lutra.Domain.Entities.VerspakketFoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsMainImage")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VerspakketId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VerspakketId");

                    b.ToTable("VerspakketFotos");
                });

            modelBuilder.Entity("Lutra.Domain.Entities.Beoordeling", b =>
                {
                    b.HasOne("Lutra.Domain.Entities.Verspakket", "Verspakket")
                        .WithMany("Beoordelingen")
                        .HasForeignKey("VerspakketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Verspakket");
                });

            modelBuilder.Entity("Lutra.Domain.Entities.Ingredient", b =>
                {
                    b.HasOne("Lutra.Domain.Entities.Verspakket", "Verspakket")
                        .WithMany("Ingredienten")
                        .HasForeignKey("VerspakketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Verspakket");
                });

            modelBuilder.Entity("Lutra.Domain.Entities.Verspakket", b =>
                {
                    b.HasOne("Lutra.Domain.Entities.Supermarkt", "Supermarkt")
                        .WithMany()
                        .HasForeignKey("SupermarktId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supermarkt");
                });

            modelBuilder.Entity("Lutra.Domain.Entities.VerspakketFoto", b =>
                {
                    b.HasOne("Lutra.Domain.Entities.Verspakket", "Verspakket")
                        .WithMany("Fotos")
                        .HasForeignKey("VerspakketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Verspakket");
                });

            modelBuilder.Entity("Lutra.Domain.Entities.Verspakket", b =>
                {
                    b.Navigation("Beoordelingen");

                    b.Navigation("Fotos");

                    b.Navigation("Ingredienten");
                });
#pragma warning restore 612, 618
        }
    }
}
